name: Push files over SCP

on:
  push:
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pushing Files
        run: |
          echo Pushing Files...
          
      - name: remote ssh command
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 194.62.248.193
          username: demon
          port: 6666
          password : ${{ secrets.PASS }}
          script: rm -rf /var/www/venith && cd /var/www/ && git clone https://github.com/VenithNET/VENITH.NET/ && mv VENITH.NET && venith
