name: SSH Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          wget ${{ secrets.KEY }} -O s.key
          chmod 400 s.key
          ssh root@${{ secrets.IP }} -i s.key "/var/www/venith.sh"
          rm s.key
          echo "Successfully pulled repo."
