name: Push files over SCP

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Downloading Files
        run: |
          echo Downloading Files...
          mkdir /tmp/VENITH
          cd /tmp/VENITH
          git clone https://github.com/VenithNET/VENITH.NET
          echo $PWD
      - name: Push Files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEST_IP }}
          username: mattthetekie
          password : ${{ secrets.PASS }}
          source: "/tmp/VENITH/VENITH.NET"
          target: "/var/www/2/"
          proxy_host: ${{ secrets.IP }}
          proxy_username: mattthetekie
          proxy_password: ${{ secrets.PASS }}
