name: Push over SCP

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Getting Ready...
        run: |
          echo "Getting Ready..."
          mkdir -p ~/.ssh/
          echo "HOST *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pushing Files...
        run: |
          echo "Pushing Files..."
          ${{ secrets.TEST }}
