name: Push files over SCP

on:
  push:
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Deploy
        run: |
           TEMP=$(mktemp)
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > $TEMP
           ssh -o 'StrictHostKeyChecking no' -i $TEMP mattthetekie@venith.net 'bash -s' < "mkdir /var/www/venith && rm -rf /var/www/venith && cd /var/www/ && git clone https://github.com/VenithNET/VENITH.NET/ && mv VENITH.NET venith"
