  - name: copy file via ssh key
    uses: appleboy/scp-action@master
    with:
      host: ${{ secrets.TEST_SERVER_HOST }}
      username: ${{ secrets.TEST_SERVER_USERNAME }}
      password : ${{ secrets.TEST_SERVER_PASSWORD }}
      proxy_host: ${{ secrets.JUMP_SERVER_HOST }}
      proxy_username: ${{ secrets.JUMP_SERVER_USERNAME }}
      proxy_key: ${{ secrets.JUMP_SERVER_KEY }}
      proxy_passphrase: ${{ secrets.JUMP_SERVER_KEY_PASSPHRASE }}
      source: "docker-compose.yml,.env"
      target: ${{ env.DEPLOYMENT_PATH }}

  - name: Executing remote ssh commands using ssh key
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.TEST_SERVER_HOST }}
      username: ${{ secrets.TEST_SERVER_USERNAME }}
      password : ${{ secrets.TEST_SERVER_PASSWORD }}
      proxy_host: ${{ secrets.JUMP_SERVER_HOST }}
      proxy_username: ${{ secrets.JUMP_SERVER_USERNAME }}
      proxy_key: ${{ secrets.JUMP_SERVER_KEY }}
      proxy_passphrase: ${{ secrets.JUMP_SERVER_KEY_PASSPHRASE }}
      script: pwd
