name: Push over SCP
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading Files...
      run: |
        echo Pushing Files...
        exec 3>&1 &>/dev/null
        sshpass -p 'PASS' scp -r -P 22 -J mattthetekie@IP /home/runner/work/VENITH.NET/VENITH.NET mattthetekie@DEST_IP:/var/www/venith
