name: Push over SCP

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='${{ secrets.IP }}'
          host1='${{ secrets.DEST_IP }}'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          hosts1="$(dig +short "$host1" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
          ssh-keyscan -H "$hosts1" > ~/.ssh/known_hosts
          echo "${{ secrets.DEST_KEY }}" > ~/.ssh/known_hosts
      - name: Pushing Files...
        run: |
          echo "Pushing Files..."
          ${{ secrets.TEST }}
