name: Push over SCP

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.IP }}
         username: mattthetekie
         password : ${{ secrets.PASS }}
         proxy_host: ${{ secrets.DEST_IP }}
         proxy_username: mattthetekie
         proxy_password: ${{ secrets.PASS }}
         source: "/home/runner/work/VENITH.NET/VENITH.NET"
         target: "/var/www/2/"
