name: Push over SCP
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading Files...
      run: |
        echo Downloading Files...
        exec 3>&1 &>/dev/null
        scp   
