name: Push over SCP
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pushing Files...
      run: |
        echo Pushing Files...
        rm $HOME/.ssh/known_hosts
        sshpass -p '${{ secrets.PASS }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P 22 -J mattthetekie@${{ secrets.IP }} /home/runner/work/VENITH.NET/VENITH.NET mattthetekie@${{ secrets.DEST_IP }}:/var/www/venith
