name: SSH Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          wget ${{ secrets.KEY }} -O test.sh
          chmod +x test.sh
          "./test.sh"
          rm test.sh
          echo "Successfully pulled repo."
